const mapStudyGroup = (group) => ({
  id: group.id,
  name: group.name,
  subject: group.subject,
  description: group.description,
  createdBy: group.created_by,
  maxMembers: group.max_members,
  isActive: Boolean(group.is_active),
  createdAt: group.created_at,
  updatedAt: group.updated_at,
  academyId: group.academy_id != null ? Number(group.academy_id) : null,
  academyName: group.academy_name || null,
  matchingGuide: group.matching_guide || null,
  memberCount: group.member_count != null ? Number(group.member_count) : undefined,
  myRole: group.my_role || undefined,
  leaderName: group.leader_name || undefined,
});

const mapStudySession = (session) => ({
  id: session.id,
  studyGroupId: session.study_group_id,
  topicTitle: session.topic_title,
  topicDescription: session.topic_description,
  scheduledStartAt: session.scheduled_start_at,
  studyDurationMinutes: session.study_duration_minutes != null ? Number(session.study_duration_minutes) : 0,
  studyStartedAt: session.study_started_at || null,
  aiReviewedAt: session.ai_reviewed_at || null,
  startedAt: session.started_at,
  endedAt: session.ended_at,
  status: session.status,
  createdBy: session.created_by,
  createdAt: session.created_at,
  updatedAt: session.updated_at,
  groupName: session.group_name || undefined,
  subject: session.subject || undefined,
  attendanceCount: session.attendance_count != null ? Number(session.attendance_count) : undefined,
  presentCount: session.present_count != null ? Number(session.present_count) : undefined,
  lateCount: session.late_count != null ? Number(session.late_count) : undefined,
  absentCount: session.absent_count != null ? Number(session.absent_count) : undefined,
});

const mapAttendance = (attendance) => ({
  id: attendance.id,
  studySessionId: attendance.study_session_id,
  userId: attendance.user_id,
  attendanceStatus: attendance.attendance_status,
  checkedInAt: attendance.checked_in_at,
  checkedOutAt: attendance.checked_out_at,
  participationMinutes: attendance.participation_minutes,
  createdAt: attendance.created_at,
  updatedAt: attendance.updated_at,
  userName: attendance.user_name || undefined,
  loginId: attendance.login_id || undefined,
  topicTitle: attendance.topic_title || undefined,
  groupName: attendance.group_name || undefined,
});

const mapStudyRecruitment = (recruitment) => ({
  id: recruitment.id,
  academyId: recruitment.academy_id != null ? Number(recruitment.academy_id) : null,
  academyName: recruitment.academy_name || null,
  academyAddress: recruitment.academy_address || null,
  title: recruitment.title,
  targetClass: recruitment.target_class || null,
  reviewScope: recruitment.review_scope || null,
  aiTopicExamples: recruitment.ai_topic_examples || null,
  recruitmentStartAt: recruitment.recruitment_start_at,
  recruitmentEndAt: recruitment.recruitment_end_at,
  minApplicants: recruitment.min_applicants != null ? Number(recruitment.min_applicants) : null,
  maxApplicants: recruitment.max_applicants != null ? Number(recruitment.max_applicants) : null,
  teamSize: Number(recruitment.team_size || 0),
  matchingGuide: recruitment.matching_guide || null,
  applicationCheckConfig: recruitment.application_check_config || null,
  status: recruitment.status,
  createdBy: recruitment.created_by || null,
  createdAt: recruitment.created_at,
  updatedAt: recruitment.updated_at,
});

const mapStudyRecruitmentApplication = (application) => ({
  id: application.id,
  recruitmentId: application.recruitment_id,
  userId: application.user_id,
  participationIntent: application.participation_intent,
  availableTimeSlots: application.available_time_slots || null,
  preferredStyle: application.preferred_style || null,
  mbtiType: application.mbti_type || null,
  customResponses: application.custom_responses || null,
  presentationLevel: application.presentation_level,
  createdAt: application.created_at,
  updatedAt: application.updated_at,
});

module.exports = {
  mapStudyGroup,
  mapStudySession,
  mapAttendance,
  mapStudyRecruitment,
  mapStudyRecruitmentApplication,
};
